stages:
  - tests
  - deploy

lint-tests:
  stage: tests
  image:
    name: docker.io/chrisnt5/kubevious-cli:1.0.0
  script:
    - kubevious guard k8s --detailed --ignore-unknown --ignore-patterns

# build-image:
#   stage: build
deploy-app:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  # before_script:
  #   # Use the K8s Kubeconfig file from the Project/Settings/CICD/Variables section
  #   - export KUBECONFIG=$KUBECONFIG_FILE
  script:
    - kubectl config get-contexts
    - kubectl config use-context christi4n/hello-go:agent-hello-go 
    - kubectl create namespace $APP_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
