apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-go
  name: hello-go
spec:
  type: LoadBalancer
  ports:
  - nodePort: 32435
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: hello-go
  sessionAffinity: None