deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context basic-dev-cluster:gitlab-agent-agent-hello-go
    - kubectl get pods